
# avec sudo ansible-playbook -c local config.vm3.yml
---
- hosts: localhost
  tasks:

    # adresse IPv4 avec nmcli (CLI pour NetworkManager)
    # NB cette configuration est automatiquement appliquée
    ###############################################################
    # suppression route par défaut (de vagrant)
    - shell: ip route del default
    #  ignore_errors: True # permet à ansible de continuer

    # Suppression de la connexion par défaut
    - shell: nmcli connection del "Connexion filaire 1"
    # Facultatif, pour supprimer une connexion déjà configurée, faire
    - shell: nmcli connection del ansible-eth1
      ignore_errors: True # permet à ansible de continuer

    # Paramètres réseaux pour VM3
    # ifname (interface réseau) : eth1
    # con-name (nom de la connexion dans NM) : ansible-eth1
    # type : ethernet
    # ip4 (adresse/prefixe IPv4) : 172.16.2.163/28
    # gw4 (adresse passerelle IPv4) : 172.16.2.162
    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip4 172.16.2.163/28 gw4 172.16.2.162

