
# avec sudo ansible-playbook -c local config.vm1.yml
---
- hosts: localhost
  tasks:

    # adresse IPv4 avec nmcli (CLI pour NetworkManager)
    # NB cette configuration est automatiquement appliquée
    ###############################################################
    # suppression route par défaut (de vagrant)
    - shell: ip route del default
      ignore_errors: True # permet à ansible de continuer

    # Suppression de la connexion par défaut
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection del "Connexion filaire 2"
      ignore_errors: True # permet à ansible de continuer
    # Facultatif, pour supprimer une connexion déjà configurée, faire
    - shell: nmcli connection del ansible-eth1
      ignore_errors: True # permet à ansible de continuer
    - shell: nmcli connection del ansible-eth2
      ignore_errors: True # permet à ansible de continuer
    # Paramètres réseaux pour VM1
    # ifname (interface réseau) : eth1
    # con-name (nom de la connexion dans NM) : ansible-eth1
    # type : ethernet
    # ip4 (adresse/prefixe IPv4) : 172.16.2.186
    # gw4 (adresse passerelle IPv4) : ???
    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip4 172.16.2.186/28 gw4 172.16.2.183

    - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip6 fc00:1234:2::36/64 gw6 fc00:1234:2::26
