
# avec sudo ansible-playbook -c local config.vm3.yml
---
- hosts: localhost
  tasks:

    - shell: ip route del default
      ignore_errors: True
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True
    - shell: nmcli connection del "Connexion filaire 2"
      ignore_errors: True
    - shell: nmcli connection del ansible-eth1
      ignore_errors: True
    - shell: nmcli connection del ansible-eth2
      ignore_errors: True

    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip4 172.16.2.163/28 gw4 172.16.2.162

    - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip4 172.16.2.183/28 gw4 172.16.2.186

    - shell: ip route add default via 172.16.2.186 dev eth2
